# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-27 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posts',
            table='posts',
        ),
        migrations.AlterModelTable(
            name='postslike',
            table='posts_like',
        ),
    ]
